### ISSUE TITLE
Support `TorchTensorField`

### ISSUE THREAD

**Issue by carmocca** [libffcv/ffcv#101]
There should be a counterpart to `NDArrayField` for torch Tensors. This would be useful to convert existing `torch.utils.data.Dataset`s to `.beton`.

Following the API described in this guide: https://docs.ffcv.io/writing_datasets.html#writing-a-dataset-to-ffcv-format

```python
dataset = Dataset(...)
fields = {"covariate": TorchTensorField(shape=..., dtype=torch.float32)}
writer = DatasetWriter(dataset_path, fields)
writer.from_indexed_dataset(dataset)
```

Using `NDArrayField` currently fails with:

```python
  File "/home/carlos/miniconda3/envs/ffcv/lib/python3.8/site-packages/ffcv/fields/ndarray.py", line 94, in encode
    data_region[:] = field.reshape(-1).view('<u1')
TypeError: view() received an invalid combination of arguments - got (str), but expected one of:
 * (tuple of ints size)
      didn't match because some of the arguments have invalid types: (str)
 * (torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (str)
```

**Comment by GuillaumeLeclerc** [comment]
I think it would just be easier to just check the type and convert tensors as part of the encode procedure of the NDarray field. Thoughts ?

I could also add what you suggest and make it extend NDarray field. 

Any preference ? (Both are super easy and I'll add that in the next release for sure)

**Comment by carmocca** [comment]
I think the added class (even if it's a minimal extension) is the simplest option

**Comment by GuillaumeLeclerc** [comment]
Trying to balance ICML submissions and adding features to FFCV but I'll try to have this today.

**Comment by GuillaumeLeclerc** [comment]
Sorry for the ICML delay. This should land in v0.0.4 (possibly release candidate tonight)
