### ISSUE TITLE
Ambiguous exception during package setup

### ISSUE THREAD

**Issue by bsmietanka** [libffcv/ffcv#107]
When installing the package, e.g. via pip, and there's no `libturbojpeg` or `opencv4` package an ambiguous bare Exception() is raised, without any information about what went wrong:

https://github.com/libffcv/ffcv/blob/3d8eb68017519a6a6fb33c87491021f80bbcf0e5/setup.py#L18

**Comment by andrewilyas** [comment]
Hi! We will get to this soon---feel free to submit a PR.

**Comment by bsmietanka** [comment]
Thanks, I submitted a PR
