### ISSUE TITLE
Cannot find how DDP DistrubutedSampler works in ffcv

### ISSUE THREAD

**Issue by Kwentar** [libffcv/ffcv#122]
Hi, in DDP training we have DistributedSampler which has `.set_epoch` method (https://pytorch.org/docs/stable/data.html) 
It looks like:
```
>>> for epoch in range(start_epoch, n_epochs):
...     if is_distributed:
...         sampler.set_epoch(epoch)
...     train(loader)
```
How does it work here? Do we need do something for each epoch or we can just remove `sampler.set_epoch` while migrating to ffcv?

**Comment by GuillaumeLeclerc** [comment]
Hi @Kwentar

We do not require that in FFCV, just use it normally. Please refer to our imagenet example which supports distributed training
