### ISSUE TITLE
Tried allocating 144000000 but page size is {self.page_size}

### ISSUE THREAD

**Issue by H-B-L** [libffcv/ffcv#135]
Hi,

I am trying to convert my dataset into ffcv format. There are 3 inputs, img, ldx and, ldy. img has size (2, 600, 600), ldx has size(100,1,600,600) and, ldy has same size as ldy. Output has size (100,600,600) and all the inputs and outputs are float32. Witer works fine but writer.from_indexed_dataset(train_dataset) throws error: 

 "Tried allocating 144000000 but page size is {self.page_size}".

```
from dataset import dataset

num=20
train_dataset = dataset(num, is_train=True)

write_path = '/ffcv_test/d.beton'

for img, ldx, ldy, output in train_dataset:
       writer = DatasetWriter(write_path, {
        'img': NDArrayField(shape=(2, 600, 600), dtype=np.dtype('float32')),
        'ldx': NDArrayField(shape=(100,1, 600, 600), dtype=np.dtype('float32')),
        'ldy': NDArrayField(shape=(100, 1, 600, 600), dtype=np.dtype('float32')),
        'output': NDArrayField(shape=(100,600,600), dtype=np.dtype('float32')),
        }, num_workers=16)    

writer.from_indexed_dataset(train_dataset)
```

**Comment by GuillaumeLeclerc** [comment]
Your samples are more than 8MB: Which is the default in FFCV. In your case you need to set your page size to be a multiple of 416 MB. (See the options on the `DatasetWriter` class).

**Comment by H-B-L** [comment]
@GuillaumeLeclerc , thanks for your comment. Can you please provide me a link how to change the page size? I could not find it in the repository.

**Comment by GuillaumeLeclerc** [comment]
https://docs.ffcv.io/api/writer.html

**Comment by H-B-L** [comment]
@GuillaumeLeclerc thanks for your help. I changed MIN_PAGE_SIZE = 1 << 21 to  MIN_PAGE_SIZE = 1 << 31 and worked. but when I am trying to load data with loader like below:

```

from ffcv.loader import Loader, OrderOption
from ffcv.fields.decoders import NDArrayDecoder, FloatDecoder
from ffcv.loader import OrderOption
from ffcv.transforms import ToTensor

batch_size = 8
num_workers = 8

ORDERING = OrderOption.RANDOM

PIPELINES = {
  'img': [NDArrayDecoder(), ToTensor()],
  'ldx': [NDArrayDecoder(), ToTensor()],
  'ldy': [NDArrayDecoder(), ToTensor()],
  'output': [NDArrayDecoder(), ToTensor()]
}

write_path = '/ffcv_test/d.beton'

loader = Loader(write_path,
                batch_size=batch_size,
                num_workers=num_workers,
                order=ORDERING,
                pipelines=PIPELINES)

```

raised with error: 
  File "/home/user/anaconda3/lib/python3.9/site-packages/ffcv/memory_managers/base.py", line 52, in __init__
    page_size_bit_location = int(np.log2(reader.page_size))
OverflowError: cannot convert float infinity to integer

I printed 'self.page_size = header['page_size']' in Reader class and it was zero!

**Comment by GuillaumeLeclerc** [comment]
@H-B-L  Why would you change FFCV code when there is an argument that you can simply pass to the `DatasetWriter` ? 

```
class ffcv.writer.DatasetWriter(fname: str, fields: Mapping[str, [ffcv.fields.base.Field](https://docs.ffcv.io/api/fields.html#ffcv.fields.Field)], page_size: int = 8388608, num_workers: int = - 1)
```

**Comment by H-B-L** [comment]
@GuillaumeLeclerc  Thanks for mentioning that, later I used the argument.

**Comment by H-B-L** [comment]
@GuillaumeLeclerc Since my dataset is large I use os_cache=False, QUASI_RANDOM and raised with error below

/home/user/anaconda3/lib/python3.9/site-packages/ffcv/memory_managers/process_cache/manager.py:36: RuntimeWarning: divide by zero encountered in log2
  page_size_log2 = np.uint32(np.log2(page_size))

Please note that when I am not passing these arguments, Loader works fine for small part of data but if increase number of samples it freezes after epoch 0.

**Comment by GuillaumeLeclerc** [comment]
Which arguments? They're should be a single one. Make sure toi don't change
the global variables like you suggested earlier on. It seems that you page
size is zero here. Are you sure the value you passed is a multiple of 2MB ?

quasi random shouldn't matter in your case you can use regular random. Your
samples are so big that it doesn't matter. The goal of quasi random is to
group the samples a little so that you don't need to keep too baby pages in
ram but in you case your sample fill a whole page so as soon as you trained
on it it can be discarded so you don't have memory overhead.

**Comment by H-B-L** [comment]
@GuillaumeLeclerc You can download minimal complete script and dummy input and output data from this [repository](https://github.com/H-B-L/FFCV-Dummy-Dataset/tree/master). I change the size of data from (100,600,600) to (10,60,60) to be able to push it into repository. For me FFCV_loader throws this error :

File "/home/user/anaconda3/lib/python3.9/site-packages/ffcv/memory_managers/base.py", line 52, in __init__
    page_size_bit_location = int(np.log2(reader.page_size))
OverflowError: cannot convert float infinity to integer

**Comment by GuillaumeLeclerc** [comment]
Sorry for the delay. I'm looking at the bug right now

**Comment by GuillaumeLeclerc** [comment]
Hello, your issue is that your page size is 4GB not 409MB as your comment suggest. The maximum page size for FFCV is currently 2GB. I will throw an error in the next version if you pass a page size bigger than 2GB

**Comment by realliyifei** [comment]
After I define the `page_size` in the dataest writer and generate the `beton` data, the loader will stop in the middle. 

Is there any corresponding stuff to add in the pipeline after I changed the page\_size of the dataset writer?
