### ISSUE TITLE
OrderOption.QUASI_RANDOM seems not to be deterministic given seed

### ISSUE THREAD

**Issue by dpaleka** [libffcv/ffcv#140]
Here is the modified ffcv-imagenet demo, on Imagenette, with two loaders on the same file initialized with the same parameters.

https://gist.github.com/dpaleka/97101b99dcb055aa6526fe37dbe6897d

The two loaders produce (slightly) different first batches.

**Comment by GuillaumeLeclerc** [comment]
Thank you for the report. This is not expected and I will take a look.

**Comment by GuillaumeLeclerc** [comment]
Hello @dpaleka I don't have this dataset. Is there a way you could provide an example that uses randomly generated data so that I can run it on my local machine without downloading anything ?

**Comment by dpaleka** [comment]
Root cause is #163.
