### ISSUE TITLE
Operation between fields.

### ISSUE THREAD

**Issue by erow** [libffcv/ffcv#147]
I find it difficult to conduct operations between fields. In my case, a sample consists of two images: A and B. I have to ensure the consistency of the operations on the two images. For instance, I can easily implement it on the PyTorch style dataset:
```python
i, j, h, w = get_crop_c(height, width, scale, ratio)

resize_crop_c(temp_buffer, i, i + h, j, j + w,
             A)

resize_crop_c(temp_buffer, i, i + h, j, j + w,
              B)
```

Is it possible to use the same random crop on two fields?

**Comment by GuillaumeLeclerc** [comment]
HI! This will be easier in the next release. You can already play with this with the `new_codegen` branch (currently being tested)
