### ISSUE TITLE
Dataloader crashes when using torchvision style custom transform (random brightness)

### ISSUE THREAD

**Issue by Jasonlee1995** [libffcv/ffcv#149]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/49643709/153827376-20fea533-8288-4c26-a674-310260c63115.png">

Following the [ffcv doc](https://docs.ffcv.io/making_dataloaders.html), I made random bright augmentation using PIL Image reference using keras and pytorch augmentation. (torchvision transform style)
([keras](https://github.com/keras-team/keras-preprocessing/blob/f199f411904c2939ed110938af28f0bb372ecb2a/keras_preprocessing/image/affine_transformations.py#L215), [pytorch](https://github.com/pytorch/vision/blob/9ae0169dd0ce815eebf1aff2963e8e1eb580eb3e/torchvision/transforms/functional_pil.py#L54))

<img width="819" alt="image" src="https://user-images.githubusercontent.com/49643709/153839569-bfc0f09b-52e0-4e88-86b4-6027af4948bb.png">

I make pipeline with ffcv transformation and also the above augmentation and call dataloader.

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/49643709/153828194-2f5fa2f6-392a-485e-95af-8e4566b55d32.png">

I got the above error and tried a lot, but can't find how to solve it.
(I checked ImageDecoder output is numpy array)

<img width="680" alt="image" src="https://user-images.githubusercontent.com/49643709/153829029-10493134-b057-45b7-bc89-786f612a506c.png">

I'm currently using ffcv 0.0.3 version

**Comment by andrewilyas** [comment]
Hi @Jasonlee1995 ! Torchvision augmentations operate on Tensors and not numpy arrays, so you should move the augmentations to come after the "ToTensor" operation in your pipelines.

**Comment by Jasonlee1995** [comment]
@andrewilyas 

<img width="716" alt="image" src="https://user-images.githubusercontent.com/49643709/153978512-bd229622-82d6-4070-8e96-bf5c4ac6ceb0.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/49643709/153979652-272cc25e-734d-4d28-9574-333aa38ff15f.png">

Thanks to your advice, I change my augmentation operation to tensor not numpy and change the pipeline order.
([reference pytorch codes](https://github.com/pytorch/vision/blob/0db67d857d612b8b5f196d1b9e1314d07b8a7a29/torchvision/transforms/functional.py#L225))

But what I get is error about wrong shape and check the shape.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/49643709/153978659-261a638b-1839-46f8-9c9d-2aab6c6188fb.png">


I know that pytorch works on individual image not batch images, which mean printed shape should be (C, H, W) or (H, W, C).
(cause I add print code on augmentation code)

But what I got is (batch size, H, W, C) and I think it's strange.


If I use my own augmentation operation (torchvision style) and want my operation to work on ffcv pipeline, I have to assume that batch images are the input?

**Comment by Jasonlee1995** [comment]
Thanks! 
I find the ways not using PIL Image, but use numpy to augment the images using brightness, contrast, saturation.
As soon as I test my FFCV transformations, I'll send pull request!
