### ISSUE TITLE
Git tag for v0.0.3

### ISSUE THREAD

**Issue by samuela** [libffcv/ffcv#158]
I see that there's a release tagged for v0.0.3rc1, but no tag for release v0.0.3 which is currently that latest [release on pypi](https://pypi.org/project/ffcv/0.0.3/#history). Would it be possible to get a git tag for v0.0.3?

Having git tags for releases makes it a lot easier for others to package ffcv, eg in [Nixpkgs](https://github.com/nixos/nixpkgs).

**Comment by GuillaumeLeclerc** [comment]
Sure!

**Comment by samuela** [comment]
Thanks @GuillaumeLeclerc !

**Comment by samuela** [comment]
Huh for some reason the download is not working for me. Opening https://github.com/libffcv/ffcv/archive/v0.0.3.tar.gz gives me
```
the given path has multiple possibilities: #<Git::Ref:0x00007f5296528a88>, #<Git::Ref:0x00007f529652f748>
```
I've never seen this before...

**Comment by samuela** [comment]
Perhaps the git tag was created with a SHA prefix that is not unique within this repo?

**Comment by GuillaumeLeclerc** [comment]
Whoa that would be extremely unlikely. No idea how to fix it :(

**Comment by GuillaumeLeclerc** [comment]
`https://github.com/libffcv/ffcv/archive/refs/tags/v0.0.3.tar.gz` works for me.

**Comment by samuela** [comment]
Unfortunately I'm working with existing automation that hits the https://github.com/libffcv/ffcv/archive/v0.0.3.tar.gz endpoint whether I like it or not. 

I have a workaround for the time being, but it's an interesting failure I'd never seen before.

**Comment by GuillaumeLeclerc** [comment]
The weird thing is that if you refresh the page you get a different hash. Maybe worth reporting to github ?

**Comment by samuela** [comment]
Oh that is very odd! I hadn't noticed that the hashes change!

**Comment by GuillaumeLeclerc** [comment]
Looks cool! Thanks for integrating FFCV

**Comment by GuillaumeLeclerc** [comment]
(I hope you are not spending too much time on v0.0.3 as I hope to release v1.0.0-rc1 before the end of the week.

**Comment by samuela** [comment]
ooh, exciting! shouldn't be a problem unless there are significant changes to the dependencies or build system

**Comment by GuillaumeLeclerc** [comment]
No just adding new features
