### ISSUE TITLE
Some dependencies are incorrect/unnecessary

### ISSUE THREAD

**Issue by samuela** [libffcv/ffcv#159]
* `sklearn` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L55). But this should likely be `scikit-learn`. Also it does not appear to be used [anywhere in the actual ffcv source](https://github.com/libffcv/ffcv/search?q=sklearn&type=).
* `matplotlib` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L54) but does not appear to be used [anywhere in the actual ffcv source](https://github.com/libffcv/ffcv/search?l=Python&q=matplotlib&type=).
* `fastargs` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L53) but is [only used in the cifar example code](https://github.com/libffcv/ffcv/search?q=fastargs&type=).
* `imgcat` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L56) but is not used in the [actual ffcv source](https://github.com/libffcv/ffcv/search?q=imgcat&type=).
* `assertpy` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L58) but is only used in the [tests and benchmarks](https://github.com/libffcv/ffcv/search?l=Python&q=assertpy&type=).
* `psutil` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L60) but is only [used in the tests](https://github.com/libffcv/ffcv/search?l=Python&q=psutil&type=).
* `webdataset` is declared as a dependency [here](https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L61), but is [identified as optional in the code](https://github.com/libffcv/ffcv/blob/b390f8e0ce6cb3396fe2c66ee4a8df451586e0ef/ffcv/writer.py#L23).

**Comment by samuela** [comment]
* `numba` is not declared as a dependency, but [is necessary](https://github.com/libffcv/ffcv/blob/b390f8e0ce6cb3396fe2c66ee4a8df451586e0ef/ffcv/pipeline/compiler.py#L2).

**Comment by GuillaumeLeclerc** [comment]
Good catch @samuela. Some should definitely be removed. However:

- I don't think we want `numba` to be in the python dependencies as we recommend using it with conda. It includes packages that improve performance over the `pip` version.
- Having the packages required for to run examples was to make it easier for newcomers to just try the library by running the examples and not having to figure out what else they need to install. Do you think it's a bad idea.

Do you want to make a PR ?

**Comment by samuela** [comment]
I don't have bandwidth to submit a PR atm, but hopefully recording these things here will be useful for someone in the future.

Another one:
* OpenCV is not listed as a dependency but it is used [here](https://github.com/libffcv/ffcv/blob/bfd9b3d85e31360fada2ecf63bea5602e4774ba3/ffcv/fields/rgb_image.py#L5).

**Comment by samuela** [comment]
> Having the packages required for to run examples was to make it easier for newcomers to just try the library by running the examples and not having to figure out what else they need to install. Do you think it's a bad idea.

I would propose having separate dependency lists for the core library, benchmarks, and tests.

**Comment by GuillaumeLeclerc** [comment]
The thing here is that we want to make it as easy for people to run the experiments. If we add an extra step it will already put a lot of people off using it :/

**Comment by GuillaumeLeclerc** [comment]
I improved the list in the next release. Reopen if you have another suggestion :)
