### ISSUE TITLE
Loader.__len__ is not a pure function

### ISSUE THREAD

**Issue by dpaleka** [libffcv/ffcv#163]
Counterintuitively, calling `len()` on a `ffcv.loader.Loader` instance modifies its internal state:
https://github.com/libffcv/ffcv/blob/bfd9b3d85e31360fada2ecf63bea5602e4774ba3/ffcv/loader/loader.py#L253-L258

This causes the bug in #140 when paired with `OrderOption.QUASI_RANDOM`.
I suppose the culprit is this line:
https://github.com/libffcv/ffcv/blob/bfd9b3d85e31360fada2ecf63bea5602e4774ba3/ffcv/traversal_order/quasi_random.py#L24

**Comment by GuillaumeLeclerc** [comment]
Thanks @dpaleka It should be an easy fix :)

**Comment by GuillaumeLeclerc** [comment]
Thanks for the report, it will be in the next release
