### ISSUE TITLE
Issues with DDP with FFCV dataloader

### ISSUE THREAD

**Issue by Jasonlee1995** [libffcv/ffcv#170]
![image](https://user-images.githubusercontent.com/49643709/155356578-2b9875c5-20c5-4344-a6b0-80b34e013265.png)

I used the [ffcv imagenet codes](https://github.com/libffcv/ffcv-imagenet) and use it to my dataset.

What I experienced DDP with pytorch dataset and dataloader, they use mostly the same vram (balanced)

However when I use with FFCV dataset and dataloader, they are not balanced (0 gpu is getting way more vram than others)

Is this normal when I use DDP with FFCV dataset and dataloader or it's bug?

**Comment by GuillaumeLeclerc** [comment]
Hello,

This is a well known bug and has been fixed, we haven't made a formal release yet but you can install directly from source and it should be fixed (branch 0.0.4 or 0.0.1 should work)
