### ISSUE TITLE
np.meshgrid not supported by Numba

### ISSUE THREAD

**Issue by AmmaraRazzaq** [libffcv/ffcv#173]
Hi,
I am using `np.meshgrid` function inside one of the custom transformation function that I have written using the `ffcv.pipeline.operation` class and it is giving the following error

> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Failed in nopython mode pipeline (step: nopython frontend)
> Use of unsupported NumPy function 'numpy.meshgrid' or unsupported use of the function.

**Comment by andrewilyas** [comment]
Hi! I think this is an issue better raised in Numba---it seems like there are workarounds for implementing compilable version of mesh grid, see e.g., https://stackoverflow.com/questions/70613681/numba-compatible-numpy-meshgrid.

**Comment by GuillaumeLeclerc** [comment]
I agree, we are not maintaining numba, we are just using it as a dependency.
