### ISSUE TITLE
opencv4

### ISSUE THREAD

**Issue by dskhudia** [libffcv/ffcv#182]
I was wondering why install is looking for opencv4 (https://github.com/libffcv/ffcv/blob/main/setup.py#L30 ) instead of opencv ? installing opencv on ubuntu with 'apt install libopencv-dev` installs opencv that has version > 4 but pkg_config can't find opencv4.

**Comment by GuillaumeLeclerc** [comment]
Hi @dskhudia 

It's how the package is called in `conda`. It's up to the OS (or conda) to decide how pkg-config package are named. It's just that ubuntu and conda disagree. You can either change `setup.py` to suit your environment or make a PR to have a setup.py that works in both situation.
