### ISSUE TITLE
label is list(), how to write?

### ISSUE THREAD

**Issue by Nise-2-meet-U** [libffcv/ffcv#194]
my training and testing labels are list format, e.g.
[0.123, 0.321]
how to make make them as ffcv format and write them to disk?

**Comment by andrewilyas** [comment]
I would recommend using the NDArrayField! See here for some example tutorials:

- https://docs.ffcv.io/writing_datasets.html#writing-a-dataset-to-ffcv-format
- https://docs.ffcv.io/ffcv_examples/linear_regression.html

**Comment by Nise-2-meet-U** [comment]
thanks
