### ISSUE TITLE
pip install ffcv fails!

### ISSUE THREAD

**Issue by arunpatro-meesho** [libffcv/ffcv#237]
Doing a simple `pip install ffcv` fails in many machines and OSes. Tried with linux and macos. 

Error:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/93586790/180469641-29d91a3c-476e-4bf3-aa83-c896012d87ca.png">

**Comment by andrewilyas** [comment]
Hi! Did you install the dependencies? These instructions should work:

```
conda create -n ffcv python=3.9 cupy pkg-config compilers libjpeg-turbo opencv pytorch torchvision cudatoolkit=11.3 numba -c pytorch -c conda-forge
conda activate ffcv
pip install ffcv
```

**Comment by arunpatro-meesho** [comment]
Not sure why this was not working earlier. I think this is due to some dependency resolver. `pip install ffcv numba opencv-python` works.
