### ISSUE TITLE
dataset writer support for torch tensor images

### ISSUE THREAD

**Issue by meghbhalerao** [libffcv/ffcv#318]
Hello, 
Can support be added for `torch.Tensor objects` also which could be returned by the `Dataset` object while writing dataset into `beton` format? More specifically, in this line - https://github.com/libffcv/ffcv/blob/main/ffcv/fields/rgb_image.py#L324 - a line could be added here like - 
```
if isinstance(image, torch.Tensor):
    image = image.cpu().detach().numpy()
```
or something similar?
Thanks and please let me know if I am missing anything.

**Comment by andrewilyas** [comment]
Closing this - let me know if this was not what you were looking for!
