### ISSUE TITLE
AttributeError: 'str' object has no attribute 'type'` in graph.py

### ISSUE THREAD

**Issue by zainsarwar865** [libffcv/ffcv#324]
I'm trying to load an ffcv dataset but I get this weird error.
`
AttributeError: 'str' object has no attribute 'type'` at line 333 of ffcv/pipeline/graph.py which goes something like this
` if next_state.device.type != 'cuda' and isinstance(operation,
                    ModuleWrapper):`

Not sure why it is of string type when it probably should be something else

**Comment by andrewilyas** [comment]
This error usually occurs when you specify a device with a string like ``"cuda:0"`` instead of a ``torch.device`` (e.g., ``torch.device('cuda:0')``

**Comment by zainsarwar865** [comment]
Thanks for the response Andrew! I fixed this issue but I still get the same error.
