### ISSUE TITLE
When will RandAugment be added?

### ISSUE THREAD

**Issue by hmgxr128** [libffcv/ffcv#326]
Hi, there! 

I really love this repo as it greatly reduces the training time. 

I am wondering when RandAugment will be officially added. I see some discussion here: https://github.com/libffcv/ffcv/pull/160, but it is still not included in the current release. If it takes a long time until the next official update, can I use this version (https://github.com/libffcv/ffcv/tree/0fa3d7c8a041fec7348025afafe6e4f6fff60f33) as a walkaround? 

Thanks a lot!

**Comment by andrewilyas** [comment]
Hi @hmgxr128 ! I believe RandAugment has been merged into the next release candidate, which will hopefully be out within 2 weeks!

**Comment by hmgxr128** [comment]
Thanks! Looking forward to the next release! I am really a fan of ffcv!
