### ISSUE TITLE
Small bug (improvement suggestion) in the quickstart doc

### ISSUE THREAD

**Issue by jnboehm** [libffcv/ffcv#348]
Reading through the [quickstart](https://docs.ffcv.io/quickstart.html), the variable `jpeg_quality` is not defined explicitly.  Since the `RGBField` uses the `raw` write mode in that example (as it's the default), I think it'd make more sense to remove the `jpeg_quality` argument from the code snippet to make things easier to grasp at the beginning.

**Comment by andrewilyas** [comment]
Fixed! https://github.com/libffcv/ffcv/commit/6c3be0cabf1485aa2b6945769dbd1c2d12e8faa7
