### ISSUE TITLE
doubt about mutli-gpu train when use   imagenet 4 gpus

### ISSUE THREAD

**Issue by daixiangzi** [libffcv/ffcv#356]
Why are 4 processes started on GPU card 0 instead of 1 process?
0   N/A  N/A   2579940      C   .../miniconda3/envs/ffcv/bin/python3.9    13724MiB |
|    0   N/A  N/A   2579941      C   .../miniconda3/envs/ffcv/bin/python3.9      414MiB |
|    0   N/A  N/A   2579942      C   .../miniconda3/envs/ffcv/bin/python3.9      414MiB |
|    0   N/A  N/A   2579943      C   .../miniconda3/envs/ffcv/bin/python3.9      414MiB |
|    1   N/A  N/A   2579941      C   .../miniconda3/envs/ffcv/bin/python3.9    13868MiB |
|    2   N/A  N/A   2579942      C   .../miniconda3/envs/ffcv/bin/python3.9    13908MiB |
|    3   N/A  N/A   2579943      C   .../miniconda3/envs/ffcv/bin/python3.9    13958MiB |

**Comment by souravdalai18** [comment]
when you load pretrained checkpoints states , use map_location to 'cpu'
