### ISSUE TITLE
any support for python3.6?

### ISSUE THREAD

**Issue by jeannotes** [libffcv/ffcv#67]
in python3.5, it appears:
    from multiprocessing import (shared_memory, cpu_count, Queue, Process, Value)
ImportError: cannot import name 'shared_memory'

will you support 3.6

**Comment by GuillaumeLeclerc** [comment]
No, it's sadly fundamentally impossible. A big part of the performance of FFCV comes from the efficient communication between the workers and is enabled by the package `multiprocessing.shared_memory`. This is for this reason that we don't have a Google Colab example yet (it only supports python 3.7)

**Comment by gsakkis** [comment]
Suggestion: add `python_requires=">=3.8"` in `setup.py` for a clearer error message at installation time.
