### ISSUE TITLE
Support for Docker?

### ISSUE THREAD

**Issue by killawhale2** [libffcv/ffcv#75]
I know that there is an installation guide using conda but I was wondering if there will be support for pre-built docker images too. I prefer to not use conda on shared servers and would very much appreciate it if there was a docker image (or dockerfile) that I can grab and quickly use. 

In the meantime, it might also serve as a short-term solution to simply put together a requirements.txt file for the main installation of ffcv so people can build their own docker images for now.

**Comment by GuillaumeLeclerc** [comment]
We are working on it

**Comment by GuillaumeLeclerc** [comment]
Pinging @Hadisalman so that he can update the post when he managed to get this working.

**Comment by Hadisalman** [comment]
Hi @killawhale2 ! We just added a [Dockerfile](https://github.com/libffcv/ffcv/blob/main/docker/Dockerfile). Please let us know if face any problems using it.

**Comment by GuillaumeLeclerc** [comment]
@Hadisalman Do we want to mention docker in the documentation or it's not worth ?

**Comment by Hadisalman** [comment]
@GuillaumeLeclerc sure we can add a note.

**Comment by Hadisalman** [comment]
Done 1d94d23a910fc44542a536274d6f52b162d62069.
