### ISSUE TITLE
What is the .beton file format?

### ISSUE THREAD

**Issue by anvarganiev** [libffcv/ffcv#78]
I am trying to use Loader for my own dataset class.  I tried:
`train_dataloader = Loader(train_dataset, batch_size=256, num_workers=8, order=OrderOption.RANDOM)`
But there was an error, then I found _Loader_ class in _ffcv_, and found parameter _fname_:
`fname: str
        Full path to the location of the dataset (.beton file format).`
So I cannot find out what is the .beton file format. Could anyone explain me, please?

**Comment by GuillaumeLeclerc** [comment]
One of the many reasons behind the speed behind FFCV is that it uses an optimized format to store the dataset. You will need to convert your dataset before loading it. Here is the relevant part of the documentation: https://docs.ffcv.io/writing_datasets.html

Feel free to reopen if you have further questions.
