### ISSUE TITLE
setup.py bugs

### ISSUE THREAD

**Issue by hyandell** [libffcv/ffcv#88]
Hi ffcv project,

I just wanted to note that the setup.py isn't noting the Apache-2.0 license, and that the url is old.

**Comment by andrewilyas** [comment]
Will put this on the TODO list---PRs welcome!

**Comment by GuillaumeLeclerc** [comment]
Thank you for pointing that out @hyandell !

**Comment by GuillaumeLeclerc** [comment]
Should be integrated in 0.0.3. Thanks @hyandell
