### ISSUE TITLE
Bug for loader with indices specified

### ISSUE THREAD

**Issue by chengxuz** [libffcv/ffcv#90]
When the distributed loader has indices specified, the returned order from the traversal_order function will be wrong. In both [Sequential](https://github.com/libffcv/ffcv/blob/main/ffcv/traversal_order/sequential.py#L30) and [Random](https://github.com/libffcv/ffcv/blob/main/ffcv/traversal_order/random.py#L27), the returned results are just relative indices always ranging from 0 to len(sampler), instead of what's stored in `indices`, I believe the correct way is to return `self.indices[np.array(list(self.sampler))]`. 

I have not checked the implementation of quasi-random, it's likely that a similar bug will also happen there.

**Comment by GuillaumeLeclerc** [comment]
Thanks for reporting! What line/file are you referring to ?

**Comment by chengxuz** [comment]
line numbers are specifed in my link to the Sequential and Random.

**Comment by GuillaumeLeclerc** [comment]
Sound great and it makes sense to me. I know it might be a lot to ask but if you could make a PR with a test that fails I would gladly fix this today

**Comment by GuillaumeLeclerc** [comment]
don't worry about it blocked some time to do it tonight myself as it's high priority

**Comment by GuillaumeLeclerc** [comment]
Fix should land in v0.0.3

PS: The bug wasn't there with QUASI_RANDOM because it actually doesn't support Distributed (created #92)
